version: "3.7"
services: 
  frontend:
    build: ./frontend
    image: frontend:latest
    ports: 
      - "80:80"
  backend:
    build: ./backend
    image: backend:latest
    ports: 
      - "8000:80"
  piproxy:
    build: ./ponyisland-proxy
    image: piproxy:latest
    ports: 
      - "9000:9000"