version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Start docker-compose
          command: docker-compose -f "docker-compose.yml" up -d --build
      - run:
          name: Wait for it to be up
          command: tools/wait-for-it.sh localhost:80
      - run:
          name: Install e2e tests
          command: npm ci
          working_directory: e2e_tests
      - run:
          name: Run Cypress e3e tests
          command: npx cypress run
          working_directory: e2e_tests
      - run:
          name: Shutdown the containers
          command: docker-compose down
      
      - store_test_results:
          path: e2e_tests/results
      - store_artifacts:
          path: e2e_tests/results
      - store_artifacts:
          path: e2e_tests/cypress/videos

workflows:
  main:
    jobs:
      - build