version: 2.1
jobs:

  test_frontend:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run:
          name: Install phpunit
          command: php composer.phar install
          working_directory: frontend
      - run:
          name: Run unit tests
          command: ./vendor/bin/phpunit --coverage-clover coverage.xml --bootstrap vendor/autoload.php
      - store_artifacts:
          path: frontend/coverage.xml          

  test_e2e:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Start docker-compose
          command: docker-compose -f "docker-compose.yml" up -d --build
      - run:
          name: Wait for it to be up
          command: tools/wait-for-it.sh localhost:80
      - run:
          name: Install e2e tests
          command: npm ci
          working_directory: e2e_tests
      - run:
          name: Run Cypress e2e tests
          command: npx cypress run
          working_directory: e2e_tests
      - run:
          name: Shutdown the containers
          command: docker-compose down
      
      - store_test_results:
          path: e2e_tests/results
      - store_artifacts:
          path: e2e_tests/results
      - store_artifacts:
          path: e2e_tests/cypress/screenshots
      - store_artifacts:
          path: e2e_tests/cypress/videos
      - store_artifacts:
          path: e2e_tests/coverage
      - store_artifacts:
          path: frontend/coverage.xml


workflows:
  main:
    jobs:
      - test_frontend
      - test_e2e:
          requires:
            - test_frontend