# Generated by Django 2.2.4 on 2019-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='id',
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
